### PR TITLE
Added Models and Database Configs.

### PR DESCRIPTION
**Pull request by christianareas**

### CODE REVIEW

**Comment by wevexOP** [comment]
Hmm, is this another .json file? Let me try and clean it up and resolve the conflicts.

**Review by wevexOP — COMMENTED** [review]
Nice, the schema is looking good!

**Comment by christianareas** [comment]
Don’t worry about conflicts, @wevexOP. I can resolve those when I go to merge. I usually pull from main before I push to GitHub.

**Review by wevexOP — COMMENTED** [review]
Noice

**Pull request merged**
